"""
Tests for demux, silence detection, and WAV slicing, against real ffmpeg.

These run on a ~2.5 s clip generated by ffmpeg itself (a tone with a known silent gap
punched into the middle), so the expected silence boundaries are known exactly rather
than eyeballed from a recording. The generated clip is 44.1 kHz stereo AAC in MP4 with a
video stream attached, so `extract_audio_16k_mono` performs the same real resample and
downmix it performs on samples/test_clip.mp4.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from src.audio import (
    AudioError,
    detect_silences,
    extract_audio_16k_mono,
    read_wav_params,
    write_wav_slice,
)
from src.config import Config
from src.stages.demux import DEMUXED_WAV_NAME, PROVENANCE_NAME, run_demux

ffmpeg_required = pytest.mark.skipif(
    subprocess.run(["ffmpeg", "-version"], capture_output=True, check=False).returncode != 0,
    reason="ffmpeg not on PATH",
)

#: The generated clip is a 440 Hz tone with this window muted, so silencedetect has a
#: ground truth to be checked against rather than a subjective one.
GAP_START_S = 1.0
GAP_END_S = 1.6
CLIP_DURATION_S = 3.0


@pytest.fixture
def tone_clip_mp4(tmp_path: Path) -> Path:
    """A 3s 44.1 kHz stereo AAC + video MP4 with a known 0.6s silent gap in the middle."""
    clip = tmp_path / "tone_with_gap.mp4"
    subprocess.run(
        [
            "ffmpeg", "-v", "error", "-nostdin", "-y",
            "-f", "lavfi", "-i", f"testsrc=size=320x240:rate=10:duration={CLIP_DURATION_S}",
            "-f", "lavfi", "-i",
            f"sine=frequency=440:duration={CLIP_DURATION_S},"
            f"volume=enable='between(t,{GAP_START_S},{GAP_END_S})':volume=0",
            "-c:v", "mpeg4", "-c:a", "aac", "-ar", "44100", "-ac", "2",
            "-shortest", str(clip),
        ],
        check=True, capture_output=True,
    )
    return clip


# --- extraction ---------------------------------------------------------------------

@ffmpeg_required
def test_extraction_converts_44k_stereo_aac_to_16k_mono_pcm(tone_clip_mp4: Path,
                                                            tmp_path: Path) -> None:
    """The demux is a real format conversion, not a container passthrough."""
    out = tmp_path / "audio.wav"

    info = extract_audio_16k_mono(tone_clip_mp4, out)

    assert info["sample_rate"] == 16000
    assert info["channels"] == 1
    assert info["codec_name"] == "pcm_s16le"
    assert info["duration_s"] == pytest.approx(CLIP_DURATION_S, abs=0.1)


@ffmpeg_required
def test_extraction_is_byte_identical_across_runs(tone_clip_mp4: Path, tmp_path: Path) -> None:
    """Deterministic output is what keeps chunk hashes, and therefore cache keys, stable."""
    first, second = tmp_path / "a.wav", tmp_path / "b.wav"

    extract_audio_16k_mono(tone_clip_mp4, first)
    extract_audio_16k_mono(tone_clip_mp4, second)

    assert first.read_bytes() == second.read_bytes()


@ffmpeg_required
def test_run_demux_reports_both_formats(tone_clip_mp4: Path, config: Config,
                                        tmp_path: Path) -> None:
    """The stage records what the source was and what it became, for the milestone report."""
    cfg = Config(**{**config.__dict__, "input_path": tone_clip_mp4,
                    "output_dir": tmp_path / "out"})

    result = run_demux(cfg)

    assert result.source.sample_rate == 44100
    assert result.source.channels == 2
    assert result.source.codec_name == "aac"
    assert result.extracted.sample_rate == 16000
    assert result.extracted.channels == 1
    assert result.wav_path.name == DEMUXED_WAV_NAME
    assert result.wav_path.exists()


@ffmpeg_required
def test_the_wav_is_reused_when_the_input_is_unchanged(tone_clip_mp4: Path, config: Config,
                                                       tmp_path: Path) -> None:
    """Reuse is what makes `--stage asr` instant, so an unchanged input must not re-extract."""
    cfg = Config(**{**config.__dict__, "input_path": tone_clip_mp4,
                    "output_dir": tmp_path / "out"})
    first = run_demux(cfg)
    stamped = first.wav_path.stat().st_mtime_ns

    run_demux(cfg)

    assert first.wav_path.stat().st_mtime_ns == stamped
    assert (cfg.output_dir / PROVENANCE_NAME).exists()


@ffmpeg_required
def test_a_wav_from_a_different_input_is_never_reused(tone_clip_mp4: Path, tiny_wav: Path,
                                                      config: Config, tmp_path: Path) -> None:
    """The bug this guards: every later stage keys off the WAV, not the video.

    Reusing another input's audio made the whole pipeline dub the wrong source entirely
    from cache and report success -- only the M6 post-mux duration check noticed.
    """
    out = tmp_path / "out"
    run_demux(Config(**{**config.__dict__, "input_path": tone_clip_mp4, "output_dir": out}))

    second = run_demux(Config(**{**config.__dict__, "input_path": tiny_wav, "output_dir": out}))

    # tiny_wav is 0.5s; the tone clip is 3s. The reused file would have been the tone clip.
    assert second.extracted.duration_s == pytest.approx(0.5, abs=0.05)
    recorded = json.loads((out / PROVENANCE_NAME).read_text(encoding="utf-8"))
    assert recorded["source_path"] == str(tiny_wav.resolve())


@ffmpeg_required
def test_a_wav_with_no_provenance_is_re_extracted(tone_clip_mp4: Path, config: Config,
                                                  tmp_path: Path) -> None:
    """A WAV of unknown origin -- left by an older version -- is not trusted."""
    cfg = Config(**{**config.__dict__, "input_path": tone_clip_mp4,
                    "output_dir": tmp_path / "out"})
    result = run_demux(cfg)
    (cfg.output_dir / PROVENANCE_NAME).unlink()
    result.wav_path.write_bytes(b"not audio at all")

    reextracted = run_demux(cfg)

    assert reextracted.extracted.duration_s == pytest.approx(CLIP_DURATION_S, abs=0.1)


@ffmpeg_required
def test_an_input_edited_in_place_is_detected(tone_clip_mp4: Path, config: Config,
                                              tmp_path: Path) -> None:
    """Provenance records size and duration too, so the same path with new content re-extracts."""
    cfg = Config(**{**config.__dict__, "input_path": tone_clip_mp4,
                    "output_dir": tmp_path / "out"})
    run_demux(cfg)

    subprocess.run(
        [
            "ffmpeg", "-v", "error", "-nostdin", "-y",
            "-f", "lavfi", "-i", "testsrc=size=320x240:rate=10:duration=1.5",
            "-f", "lavfi", "-i", "sine=frequency=440:duration=1.5",
            "-c:v", "mpeg4", "-c:a", "aac", "-ar", "44100", "-ac", "2",
            "-shortest", str(tone_clip_mp4),
        ],
        check=True, capture_output=True,
    )
    result = run_demux(cfg)

    assert result.extracted.duration_s == pytest.approx(1.5, abs=0.1)


def test_extraction_of_a_missing_file_raises(tmp_path: Path) -> None:
    """A missing input fails with the path named, not a bare ffmpeg exit code."""
    with pytest.raises(AudioError, match="does not exist"):
        extract_audio_16k_mono(tmp_path / "nope.mp4", tmp_path / "out.wav")


# --- silence detection ---------------------------------------------------------------

@ffmpeg_required
def test_silence_detection_finds_the_known_gap(tone_clip_mp4: Path, tmp_path: Path) -> None:
    """The detected span matches the window that was actually muted."""
    wav = tmp_path / "audio.wav"
    extract_audio_16k_mono(tone_clip_mp4, wav)

    silences = detect_silences(wav, threshold_db=-40.0, min_silence_s=0.20)

    gap = next(s for s in silences if s.start_s > 0.5)
    assert gap.start_s == pytest.approx(GAP_START_S, abs=0.1)
    assert gap.end_s == pytest.approx(GAP_END_S, abs=0.1)
    assert gap.midpoint_s == pytest.approx((GAP_START_S + GAP_END_S) / 2, abs=0.1)


@ffmpeg_required
def test_min_silence_longer_than_the_gap_finds_nothing(tone_clip_mp4: Path,
                                                       tmp_path: Path) -> None:
    """Raising the minimum pause length past the real gap correctly reports no cut point."""
    wav = tmp_path / "audio.wav"
    extract_audio_16k_mono(tone_clip_mp4, wav)

    silences = detect_silences(wav, threshold_db=-40.0, min_silence_s=2.0)

    assert [s for s in silences if s.start_s > 0.5] == []


@ffmpeg_required
def test_detected_silences_stay_inside_the_file(tone_clip_mp4: Path, tmp_path: Path) -> None:
    """No span may run past the end of the audio, or a chunk boundary could too."""
    wav = tmp_path / "audio.wav"
    info = extract_audio_16k_mono(tone_clip_mp4, wav)

    silences = detect_silences(wav, threshold_db=-30.0, min_silence_s=0.1)

    for span in silences:
        assert 0.0 <= span.start_s < span.end_s <= float(info["duration_s"]) + 0.01  # type: ignore[arg-type]


def test_zero_min_silence_is_rejected(tiny_wav: Path) -> None:
    """A zero-length minimum would make every sample boundary a cut candidate."""
    with pytest.raises(AudioError, match="must be > 0"):
        detect_silences(tiny_wav, min_silence_s=0.0)


# --- slicing --------------------------------------------------------------------------

def test_slice_has_the_requested_duration_and_format(tiny_wav: Path, tmp_path: Path) -> None:
    """A slice keeps the source's rate/channels and spans exactly the requested window."""
    out = tmp_path / "slice.wav"

    duration = write_wav_slice(tiny_wav, out, 0.1, 0.4)

    assert duration == pytest.approx(0.3, abs=1e-6)
    params = read_wav_params(out)
    assert params["frame_rate"] == 16000
    assert params["channels"] == 1
    assert params["frames"] == 4800


def test_consecutive_slices_tile_the_source_exactly(tiny_wav: Path, tmp_path: Path) -> None:
    """Adjacent slices must share a sample boundary, or the seam would gain or lose audio."""
    left, right = tmp_path / "l.wav", tmp_path / "r.wav"

    write_wav_slice(tiny_wav, left, 0.0, 0.2137)
    write_wav_slice(tiny_wav, right, 0.2137, 0.5)

    total = read_wav_params(left)["frames"] + read_wav_params(right)["frames"]
    assert total == read_wav_params(tiny_wav)["frames"]


def test_slicing_is_deterministic(tiny_wav: Path, tmp_path: Path) -> None:
    """The same slice written twice is byte-identical, so its cache key never changes."""
    first, second = tmp_path / "a.wav", tmp_path / "b.wav"

    write_wav_slice(tiny_wav, first, 0.1, 0.4)
    write_wav_slice(tiny_wav, second, 0.1, 0.4)

    assert first.read_bytes() == second.read_bytes()


def test_slice_past_the_end_is_clamped(tiny_wav: Path, tmp_path: Path) -> None:
    """Asking beyond the file returns what exists rather than padding with junk."""
    out = tmp_path / "slice.wav"

    duration = write_wav_slice(tiny_wav, out, 0.3, 9.0)

    assert duration == pytest.approx(0.2, abs=1e-6)


def test_inverted_slice_is_rejected(tiny_wav: Path, tmp_path: Path) -> None:
    """An end before the start is a planner bug and must not produce an empty file."""
    with pytest.raises(AudioError, match="must be after start"):
        write_wav_slice(tiny_wav, tmp_path / "x.wav", 0.4, 0.2)


def test_empty_slice_is_rejected(tiny_wav: Path, tmp_path: Path) -> None:
    """A window entirely past the end would yield a zero-frame WAV the API would reject."""
    with pytest.raises(AudioError, match="is empty"):
        write_wav_slice(tiny_wav, tmp_path / "x.wav", 5.0, 6.0)
